#     ============================================================
#     SOC LAB - Wazuh Agent Configuration
#     ============================================================
#
#     Purpose:
#     The Wazuh Agent runs on SOC-IDS-01 and collects security
#     events from the host. It forwards these events to the
#     Wazuh Manager for analysis and monitoring.
#
#    Main integrations:
#     - Suricata IDS alerts
#     - SSH authentication events
#     - Linux system logs
#
#     ============================================================ 
#
#



# Wazuh Manager connection 

<client>
  <server>
    <address>192.168.0.4</address>
    <port>1514</port>
    <protocol>tcp</protocol>
  </server>

  <config-profile>ubuntu, ubuntu24, ubuntu24.04</config-profile>
  <notify_time>20</notify_time>
  <time-reconnect>60</time-reconnect>
</client>


#     ============================================================
#     Suricata IDS Integration
#     ============================================================
#
#     The custom Suricata filtering script extracts relevant
#     security alerts from Suricata's eve.json and writes them
#     to wazuh-alerts.json.
#
#     Wazuh Agent monitors this JSON file and forwards the
#     events to the Wazuh Manager.
#     ============================================================ -->

<localfile>
  <log_format>json</log_format>
  <location>/var/log/suricata/wazuh-alerts.json</location>
</localfile>


#     ============================================================
#     SSH Authentication Monitoring
#     ============================================================
#
#     Wazuh monitors auth.log to detect Linux authentication
#     events such as failed SSH login attempts.
#     ============================================================ 

<localfile>
  <log_format>syslog</log_format>
  <location>/var/log/auth.log</location>
</localfile>
